[package]
name = "test_main"
version = "0.1.0"
edition = "2018"

[dependencies]
dygpi = { version = "0.1", path = ".." }
pretty_env_logger = "0.4"
test_api = { version = "0.1", path = "../test_api" }
